--PROJECT ON GLOBAL WORKFORCE & COMPENSATION ANALYTICS --

--CREATE THE DATABASE STRUCTURE(DDL)--
CREATE DATABASE GLOBAL_COMPENSATION_ANALYTICS; 
USE GLOBAL_COMPENSATION_ANALYTICS;

---CREATE DEPARTMENT TABLE ---
CREATE TABLE DEPARTMENT
(DEPT_ID INT PRIMARY KEY,
DEPT_NAME VARCHAR(50) NOT NULL,
BUDGET DECIMAL (12,2));

---CREATE EMPLOYEES TABLE ---
CREATE TABLE EMPLOYEES
(EMP_ID INT PRIMARY KEY,
FIRST_NAME VARCHAR(50) NOT NULL,
LAST_NAME VARCHAR(50) NOT NULL,
HIRE_DATE DATE NOT NULL,
DEPT_ID INT,
COUNTRY VARCHAR(50)NOT NULL,
STATUS VARCHAR(50) DEFAULT 'ACTIVE',
FOREIGN KEY (DEPT_ID) REFERENCES DEPARTMENT (DEPT_ID)); 

---CREATE COMPENSATION HISTORY TABLE ---
CREATE TABLE COMPENSATION_HISTORY
(COMP_ID INT PRIMARY KEY,
EMP_ID INT,
BASE_SALARY DECIMAL (10,2) NOT NULL,
BONUS DECIMAL(4,2)DEFAULT 0.00,
CHANGE_DATE DATE NOT NULL,
FOREIGN KEY (EMP_ID) REFERENCES EMPLOYEES (EMP_ID));

---CREATE PERFORMANCE REVIEW TABLE ---
CREATE TABLE PERFORMANCE_REVIEW
(REVIEW_ID INT PRIMARY KEY,
EMP_ID INT,
REVIEW_YEAR INT NOT NULL,
RATING INT CHECK (RATING BETWEEN 1 AND 5),
FOREIGN KEY (EMP_ID) REFERENCES EMPLOYEES (EMP_ID));

--INSERTION OF DATA--

INSERT INTO DEPARTMENT( DEPT_ID, DEPT_NAME, BUDGET)
VALUES(1, 'PEOPLE OPERATIONS', 500000.00),
(2, ' DATA ANALYTICS ', 850000.00),
(3, 'ENGINEERING', 2500000.00),
(4, 'MARKETING', 600000.00);
SELECT* FROM DEPARTMENT;

INSERT INTO EMPLOYEES(EMP_ID, FIRST_NAME, LAST_NAME,HIRE_DATE,DEPT_ID,COUNTRY,STATUS)
VALUES
(101, 'AMRA', 'SHARMA', '2023-01-15', 1, 'UK', 'ACTIVE'),
(102, 'LIAM', 'SMITH', '2022-06-20', 2, 'CANADA', 'ACTIVE'),
(103, 'CHLOE', 'SMITH', '2024-02-10', 2, 'FRANCE', 'ACTIVE'),
(104, 'LIVER', 'SHARMA', '2021-11-05', 3, 'UK', 'ACTIVE'),
(105, 'EMMA', 'CLARK', '2023-05-19', 3, 'CANADA', 'ACTIVE'),
(106, 'LUCAS', 'SHARMA', '2022-01-14', 3, 'FRANCE', 'TERMINATED'),
(107, 'NISA', 'CLARK', '2024-08-01', 1, 'UK', 'ACTIVE'),
(108, 'ETHAN', 'CLARK', '2023-09-10', 4, 'CANADA', 'ACTIVE'),
(109, 'MANON', 'SMITH', '2021-04-25', 4, 'FRANCE', 'ACTIVE'),
(110, 'AARAV', 'SHARMA', '2022-11-30', 2, 'UK', 'ACTIVE');
SELECT* FROM EMPLOYEES;




-- Tracking initial salaries and subsequent raises --
INSERT INTO COMPENSATION_HISTORY(COMP_ID,EMP_ID,BASE_SALARY,BONUS, CHANGE_DATE)VALUES
(1, 101, 65000.00, 5.00, '2023-01-15'),
(2, 101, 68000.00, 7.00, '2024-03-01'), -- Raise for Amara
(3, 102, 85000.00, 10.00, '2022-06-20'),
(4, 102, 85000.00, 12.00, '2023-07-01'), -- Stagnant base salary since 2023
(5, 103, 92000.00, 8.00, '2024-02-10'),
(6, 104, 105000.00, 15.00, '2021-11-05'),
(7, 104, 115000.00, 15.00, '2023-01-01'), -- No raise for Oliver in over 3 years
(8, 105, 98000.00, 10.00, '2023-05-19'),
(9, 106, 80000.00, 5.00, '2022-01-14'),  -- Terminated employee history
(10, 107, 60000.00, 0.00, '2024-08-01'),
(11, 108, 72000.00, 4.00, '2023-09-10'),
(12, 109, 78000.00, 6.00, '2021-04-25'),
(13, 109, 84000.00, 8.00, '2023-06-15'),  -- Stagnant since mid-2023
(14, 110, 88000.00, 10.00, '2022-11-30'),
(15, 110, 95000.00, 12.00, '2024-05-01');
SELECT* FROM COMPENSATION_HISTORY;

-- Challenge 1: Identifying Compensation Inequality ( WITH CTEs & Joins)----
--Problem: The Chief Human Resources Officer (CHRO) wants to find out which employees are earning significantly less than the average salary
-- for their specific department so they can adjust budgets and prevent people from quitting.

WITH DEPT_AVERAGE AS (
    SELECT 
        E.DEPT_ID,
        D.DEPT_NAME,
        AVG(C.BASE_SALARY) AS DEPT_AVERAGE_SALARY
    FROM EMPLOYEES E
    JOIN DEPARTMENT D ON E.DEPT_ID = D.DEPT_ID
    JOIN COMPENSATION_HISTORY C ON E.EMP_ID = C.EMP_ID
    WHERE C.CHANGE_DATE = (SELECT MAX(CHANGE_DATE) FROM COMPENSATION_HISTORY WHERE EMP_ID= E.EMP_ID) -- Latest salary
    GROUP BY E.DEPT_ID, D.DEPT_NAME)
SELECT  E.EMP_ID,E.FIRST_NAME, E.LAST_NAME, DA.DEPT_NAME, C.BASE_SALARY,DA.DEPT_AVERAGE_SALARY,
    (DA.DEPT_AVERAGE_SALARY - C.BASE_SALARY) AS SALARY_DEFICIT
FROM EMPLOYEES E
JOIN COMPENSATION_HISTORY C ON E.EMP_ID = C.EMP_ID
JOIN DEPT_AVERAGE DA ON E.DEPT_ID = DA.dept_id
WHERE C.BASE_SALARY < DA.DEPT_AVERAGE_SALARY
ORDER BY SALARY_DEFICIT DESC;

--Challenge 2: Employee Retention & Churn Risk Analysis (Window Functions)
-- The  Problem: We need to spot high-performing employees who are at risk of leaving because they haven't had a salary increase 
--or promotion in over 06 months.



WITH SALARY_HISTORY AS (
    SELECT 
        EMP_ID,
        BASE_SALARY,
        CHANGE_DATE,
        LAG(BASE_SALARY) OVER(PARTITION BY EMP_ID ORDER BY CHANGE_DATE) AS PREVIOUS_SALARY,
        ROW_NUMBER() OVER(PARTITION BY EMP_ID ORDER BY CHANGE_DATE DESC) AS RN
    FROM COMPENSATION_HISTORY
)
SELECT 
    E.EMP_ID,
    E.FIRST_NAME,
    E.LAST_NAME,
    E.COUNTRY,
    SH.BASE_SALARY AS CURRENT_SALARY,
    SH.CHANGE_DATE AS LAST_PAY_STUB_DATE,
    R.RATING AS LAST_PERFORMANCE_RATING
FROM EMPLOYEES E
JOIN SALARY_HISTORY SH ON E.EMP_ID = SH.EMP_ID
JOIN PERFORMANCE_REVIEW R ON E.EMP_ID = R.EMP_ID  
WHERE SH.RN = 1 
  AND R.RATING >= 4 
  AND SH.CHANGE_DATE < DATEADD(MONTH, -6, GETDATE())
ORDER BY R.RATING DESC;

SELECT EMP_ID, CHANGE_DATE FROM COMPENSATION_HISTORY;
--
SELECT 
    E.EMP_ID,
    E.FIRST_NAME,
    E.LAST_NAME,
    SH.BASE_SALARY,
    SH.CHANGE_DATE,
    SH.RN,
    R.RATING
FROM EMPLOYEES E
JOIN (
    SELECT 
        EMP_ID, BASE_SALARY, CHANGE_DATE,
        ROW_NUMBER() OVER(PARTITION BY EMP_ID ORDER BY CHANGE_DATE DESC) AS RN
    FROM COMPENSATION_HISTORY
) SH ON E.EMP_ID = SH.EMP_ID
LEFT JOIN performance_review R ON E.EMP_ID = R.EMP_ID; -- Changed to LEFT JOIN to prevent data hiding



-- First clear out any incomplete records in the reviews table
TRUNCATE TABLE performance_review;


INSERT INTO performance_review (review_id, emp_id, review_year, rating) VALUES
(1, 101, 2024, 4),
(2, 101, 2025, 4),
(3, 102, 2024, 5),
(4, 102, 2025, 5), -- Liam is our top performer
(5, 103, 2024, 3),
(6, 104, 2024, 4),
(7, 104, 2025, 5), -- Oliver is our high performer
(8, 105, 2024, 4),
(9, 107, 2025, 3),
(10, 108, 2024, 4),
(11, 109, 2024, 4),
(12, 109, 2025, 2),
(13, 110, 2024, 4),
(14, 110, 2025, 5);

WITH SALARY_HISTORY AS (
    SELECT 
        EMP_ID,
        BASE_SALARY,
        CHANGE_DATE,
        LAG(BASE_SALARY) OVER(PARTITION BY EMP_ID ORDER BY CHANGE_DATE) AS PREVIOUS_SALARY,
        ROW_NUMBER() OVER(PARTITION BY EMP_ID ORDER BY CHANGE_DATE DESC) AS RN
    FROM COMPENSATION_HISTORY
)
SELECT 
    E.EMP_ID,
    E.FIRST_NAME,
    E.LAST_NAME,
    E.COUNTRY,
    SH.BASE_SALARY AS CURRENT_SALARY,
    SH.CHANGE_DATE AS LAST_PAY_STUB_DATE,
    ISNULL(R.RATING, 0) AS LAST_PERFORMANCE_RATING -- Converts NULL to 0 for cleaner reporting
FROM EMPLOYEES E
JOIN SALARY_HISTORY SH ON E.EMP_ID = SH.EMP_ID
LEFT JOIN performance_review R ON E.EMP_ID = R.EMP_ID  -- LEFT JOIN protects your rows
WHERE SH.RN = 1 
  AND (R.RATING >= 4 OR R.RATING IS NULL) -- Catches high performers AND unrated staff at risk
  AND SH.CHANGE_DATE < DATEADD(MONTH, -6, GETDATE())
ORDER BY LAST_PERFORMANCE_RATING DESC;


--Challenge 3: International Talent Density & Cost Distribution (Aggregations)
--The Business Problem: The executive team is planning international expansion. They need a breakdown of total spending on workforce 
--costs across different regions (e.g., Canada, UK, France), showing total headcount, total payroll cost, and average performance score per country.


SELECT 
    E.COUNTRY,
    COUNT(DISTINCT E.EMP_ID) AS TOTAL_HEADCOUNT,
    -- Calculates base salary + bonus amount, substituting 0 if bonus_pct is NULL
    SUM(CH.BASE_SALARY + (CH.BASE_SALARY * (ISNULL(CH.BONUS, 0) / 100))) AS TOTAL_WORKFORCE_INVESTMENT,
    -- Averages the performance scores while rounding to 2 decimal places
    ROUND(AVG(CAST(PR.RATING AS DECIMAL(3,2))), 2) AS AVERAGE_PERFORMANCE_SCORE
FROM EMPLOYEES E
INNER JOIN (
    -- Subquery to pull only the LATEST salary record per employee
    SELECT 
        EMP_ID, 
        BASE_SALARY, 
        BONUS,
        ROW_NUMBER() OVER (PARTITION BY EMP_ID ORDER BY CHANGE_DATE DESC) as RN
    FROM COMPENSATION_HISTORY
) 
CH ON E.EMP_ID = CH.EMP_ID AND CH.RN = 1
LEFT JOIN PERFORMANCE_REVIEW PR ON E.EMP_ID = PR.EMP_ID
WHERE E.STATUS = 'Active'
GROUP BY E.COUNTRY
ORDER BY TOTAL_WORKFORCE_INVESTMENT DESC;
------------------------------------------------PROJECT END----------------------------------------------